#!/usr/bin/env bash
# venv-launch.sh — Run a Python script inside its local virtualenv, if one exists.
#
# Usage:
#   venv-launch.sh /absolute/path/to/script.py [args...]
#
# If a `venv/` directory is found next to the script, its Python interpreter
# is used. Otherwise, falls back to system Python (python3).
#
# This is used by launcher scripts auto-generated by bootstrap.sh. and allows for simple stub scripts to create a named command in ~/bin

set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 path/to/script.py [args...]" >&2
  exit 1
fi


SCRIPT_PATH="$(realpath "$1")"
shift

SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
VENV_PYTHON="$SCRIPT_DIR/venv/bin/python"

if [[ -x "$VENV_PYTHON" ]]; then
  exec "$VENV_PYTHON" "$SCRIPT_PATH" "$@"
else
  echo "⚠️  No venv found next to script. Falling back to system Python." >&2
  exec python3 "$SCRIPT_PATH" "$@"
fi
